package-lock.json, package.json, src/generate-examples-index/index.ts, test/generate-examples-index/basic.test.ts, test/generate-examples-index/broken-examples/example-1.html, test/generate-examples-index/broken-examples/examples, test/generate-examples-index/examples/example-1.html, test/generate-examples-index/examples/example-2.html, test/generate-examples-index/examples/example-alert.html, test/generate-examples-index/examples/example-confirm.html, test/generate-examples-index/examples/subdir/example-3.html, test/generate-examples-index/examples/subdir/example-4.html
Solid color screenshots result in nonzero exit code and the failed examples with solid color screenshots are listed in the output by path.
This should help to prevent issues with example screenshots being white and going unnoticed. Also it can highlight issues that render the built files unusable (though this is just a side effect, Cypress or Selenium would be much better). We can reconfigure CircleCI to fail the release if the screenshot verification fails. This would prevent issues like https://github.com/visjs/vis-network/issues/183.
=> feat: add rudimentary verification

src/generate-examples-index/content-builder/builder.ts
This adds okay to each screenshot that passes the test and fail to each that doesn't. This is handy especially in CI as it's easy to read the stdout but pretty difficult to get the screenshots from there.
```
93% - examples/network/data/scalingCustom.html
95% - examples/network/basic_usage/standalone.html
96% - examples/network/basic_usage/peer.html
97% - examples/network/basic_usage/legacy.html
98% - examples/network/basicUsage.html
100% - examples/network/exampleApplications/worldCupPerformance.html
Screenshot files for 80 written (80 files).
Verification: Only 79 passed (99 %), 1 failed.
This is not within the threshold set by --verify. Exiting with an error.
```
```
93% okay - examples/network/data/scalingCustom.html
95% okay - examples/network/basic_usage/standalone.html
96% fail - …
```
=> feat(generate-examples-index): add okay/fail to stdout

__snapshots__/test/generate-examples-index/basic.test.ts.js, src/generate-examples-index/content-builder/playground/jsfiddle.template.html, src/generate-examples-index/index.ts
Let's use secure connections whenever available. CodePen has always used HTTPS.
This also includes a small type checking fix that somehow slipped through the precommit and prepush checks in the last PR.
=> fix(generate-examples-index): use HTTPS for JSFiddle

src/module/generate-rollup-configuration/index.ts
We've never had combined node.js/browser dependencies so this was never a problem but as per visjs/vis-timeline#328 we'll need this fix from now on.
=> fix(rollup): use browser versions if available

src/module/generate-rollup-configuration/index.ts
Windows separators interfere with escaping. For this reason they decided
to use POSIX separators everywhere (they work on Windows by the way). We
don't use escaping at the moment so it's fine to just replace all
escapes (aka Windows separators) by POSIX separators.
Closes visjs/vis-timeline#419.
=> fix(gen-rollup-conf): fix globbing issues on Windows

src/module/generate-rollup-configuration/index.ts
Prior to this the last bundle bundled replaced .d.ts files of other bundler. This led to visjs/vis-network#638.
=> fix(gen-rollup-conf): don't overwrite other bundle's .d.ts

package.json, src/module/generate-rollup-configuration/index.ts
Due to recent breaking changes in Rollup PostCSS plugin that I completely missed the styles dir has moved from the root to the bundle files and is now 4 times in the packages (4 copies of the same thing). This is not how it is documented and was never announced to the public as a breaking change. This commit reverses it to the way it used to be prior to the update. It also officially drops support for Rollup PostCSS plugin (dev dep in our projects) version 2 since the way paths are interpreted is different from the up to date version 3.
=> fix(rollup-conf): styles dir location

rollup.config.js, src/module/generate-rollup-configuration/index.ts
This was a workaround for some issues around async function, but it seems that it's no longer needed.
=> fix(gen-rollup-conf): disable objectHashIgnoreUnknownHack

src/module/generate-rollup-configuration/index.ts
Regenerator runtime causes issues with CSP when used in strict mode. Once we drop IE11 support we should be able to ditch regenerator runtime and reenable strict mode.
Closes #141.
=> fix(gen-rollup-conf): disable strict mode

src/module/generate-rollup-configuration/index.ts
The CSS is injected into JS with the sourcemaps. This bloats the files without much of a benefit (they would be very rarly used, most people won't use them at all).
Saves about 50 KiB (~10%) from minified Vis Timeline.
Sourcemaps are still generated for CSS files as they're external with very little added to the CSS file itself.
Closes #104 (that tried to disable source maps for development utils, not for final consumer files).
=> fix(gen-rollup-conf): don't create CSS maps for standalone

src/module/generate-rollup-configuration/index.ts
This skips index files traversal in bundled files and requires the final file directly.
```
vis-network > vis-data/esnext/esm > vis-data/esnext/esm/vis-data.js
```
This leads to the following module systems being used:
```
ESM > ESM > ESM
```
And there's absolutely nothing wrong with that.
The problem comes with UMD:
```
vis-network > vis-data/esnext/umd > vis-data/esnext/esm/vis-data.js
```
This leads to the following module systems being used:
```
UMD > ESM > UMD
```
The consequence of this may be issues like https://github.com/visjs/vis-network/issues/688. To put it shortly tools which can't handle ESM import UMD but then are told to import ESM anyway and crash.
The middle step is removed which leads to: `ESM > ESM` or `UMD > UMD` which should work without problems.
I don't have any …
=> fix(gen-rollup-conf): bypass index files in bundled JS

src/module/generate-rollup-configuration/index.ts
The autodetection works reliably now and the workaround was actually removed from recent releases.
=> fix(gen-rollup-conf): remove obsolete workaround

.eslintignore, .eslintrc.js, tsconfig.json
The config is effectively the same, it's just changed to work with newer versions of ESLint and TS plugin.
=> test: reconfigure ESLint for upcomming updates

src/module/constants.ts
This makes the ignore pattern, which among other things prevents the polyfilling of polyfills, work with DOS and mixed DOS-POSIX paths.
Windows supports both POSIX and DOS paths. This leads to weird situations when paths are sometimes DOS, sometimes POSIX and sometimes a combination of both. It's very chaotic and unpredictable, hence the same regexp working fine in other projects but failing in Vis Network.
Seems to fix https://github.com/visjs/vis-network/issues/699, though I'm not 100% sure there's nothing else.
=> fix(babel): take DOS paths into account in ignore RE

.eslintrc.js, src/module/inspect-npm-pack.ts
Fix typo in `--dry-run` argument and provide more detailed info when something fails.
=> fix(inspect-npm-pack): fix dry run and improve error logging

babel-preset/index.js
Due to a weird quirk in the syntax of Browserlist both `or not dead` and `and not dead` are intersections with the previos part of the query. Using `or` here is very confusing as it implies that we support browsers that match one (>1% usage) or the other (not dead) but in fact they have to match both. It definitely confused me (the comment above the query is a proof of it).
This changes nothing regarding the browsers we support as in this case `(A && !B) === (A || !B)` so the list of supported and polyfilled browsers stays exactly the same. It can be verified by comparing [> 0.1% or not dead](https://browserl.ist/?q=%3E+0.1%25+or+not+dead) with [> 0.1% and not dead](https://browserl.ist/?q=%3E+0.1%25+and+not+dead).
=> fix(babel): rewrite Browserlist query

src/generate-examples-index/index.ts, test/generate-examples-index/basic.test.ts
Command:
- don't call process.exit (this forces the process to stop possibly before stderr is flushed, losing some console output), set the nonzero exit code and let the script finish normally
Test:
- print the execution output (prior to this the test case would fail with no output for debugging)
- check that generating returns with 0 status code
=> fix(generate-examples): some minor improvements

.circleci/config.yml, interop.js, package.json, public/interop/base-config.json, src/test-e2e-interop/cli.ts, src/test-e2e-interop/index.ts, src/test-e2e-interop/test.ts, src/test-e2e-interop/util.ts, tsconfig.declarations.json, tsconfig.internal.json, tsconfig.json
Parallelization took down about 4 minutes (from 45 to 41, yay!). This was a massive waste of time and with the advantage of hindsight it makes perfect sense, a lot of the stuff we run is already trying to get as much as it can from multicore systems so the utilization is already very high. Plus dependants can't start before their dependencies are done, this pretty much limits parallelization to running Network, Timeline and Graph3D in parallel and everything else in series anyway. I'm keeping it though, because it's a bit faster and since it's all based on promises now, the control flow is much nicer and easier to follow (the projects simply await the promises of their dependencies).
Bigger improvement is that it's now possible to use already built and packed project instead of building …
=> perf(interop): parallelize and accept tarballs

.circleci/config.yml, __snapshots__/test/package.test.ts.js, package.json, rollup.config.js, src/ci-utils/index.ts
At the moment it's only for installing dependencies, but it's modular so adding anything new will be as simple as adding a new command to `src/ci-utils/index.ts`. This will come in handy especially if we decide to implement E2E interop tests (which seems doable to me if #272 gets merged) so that I won't have to copy paste the same `apt-install …` commands all over the place and also manually copy paste the same fix everywhere in case the dependencies change at some point (which is quite likely because CircleCI is rolling out “next-generation” Ubuntu based images with fewer preinstalled packages, they may discontinue the chunkier Debian based ones we've been using so far).
I also removed some dependencies that seem unnecessary (it runs just fine without them), I'm not sure anymore where I …
=> feat(ci-utils): add a command for CI stuff we use in multiple repos

@types/index.d.ts, package-lock.json, package.json, rollup.config.js, src/module/generate-rollup-configuration/index.ts
BREAKING CHANGE: The way of striping code changed, though I think we never used the old way.
Quite a few things have been changed but they're all intertwined and would conflict with one another as multiple PRs.
This allows any text to be striped from production, we already had a plugin for this but it came with quite a few issues like turning `expect(x).to.be.true` into `(void 0).to.be.true`, not being able to strip methods etc. This will also allow us to use the new #properties (truly private class properties) and only expose these values in tests (in Vis Network there were a few people reporting issues related to Vue/Angular reactivity replacing everything by observers and causing weird behavior).
```typescript
Some code that will be in production and tests.
/* develblock:start */ …
```
=> feat: various improvements

src/generate-examples-index/content-builder/screenshots/index.ts
Nothing changes really, they just use different names instead of overloading based on argument type now.
=> fix(puppeteer): replace the use of a deprecated method

eslint-shareable-config/index.js
Grouping is otherwise allowed already.
=> fix(eslint-shareable-config): allow console.groupCollapsed

.circleci/config.yml, .eslintrc.js, .husky/pre-commit, __snapshots__/test/generate-examples-index/basic.test.ts.js, eslint-shareable-config/index.js, package-lock.json, package.json, public/interop/base-config.json, renovate.json, src/ci-utils/index.ts, src/generate-examples-index/cli.ts, src/generate-examples-index/content-builder/builder.ts, src/generate-examples-index/content-builder/html/index.ts, src/generate-examples-index/content-builder/playground/data.ts, src/generate-examples-index/content-builder/screenshots/index.ts, src/generate-examples-index/index.ts, src/generate-examples-index/types.ts, src/module/generate-rollup-configuration/index.ts, src/module/header.ts, src/test-e2e-interop/cli.ts, src/test-e2e-interop/index.ts, src/test-e2e-interop/test.ts, src/test-e2e-interop/util.ts, test/generate-examples-index/basic.test.ts
BREAKING CHANGE: This now relies on peer dependencies rather than
dependencies.
Using dependencies was a bit of a hack from the beginning to reduce the
amount of updates cascading through our projects (Vis Dev Utils would
carry all the dependencies it's scripts needed). Now with npm 7 the same
thing should be achievable with peer dependencies in an officially
supported way.
The projects will still work with npm 6 but npm 6 developers will have
to manually install peer dependencies (npm 6 will complain about this
during installation):
```shell
npm i --no-save \
@babel/core \
@babel/plugin-proposal-class-properties \
@babel/plugin-transform-runtime \
@babel/preset-env \
@babel/preset-typescript \
@babel/register \
@babel/runtime-corejs3 \
@rollup/plugin-commonjs \
@rollup/plugin-json \ …
```
=> feat!: update

.circleci/config.yml, package-lock.json, package.json
These are used across our projects and it makes sense to have their versions synced especially since the plugins are synced already.
=> fix(deps): make Rollup and TypeScript peers

src/test-e2e-interop/cli.ts, src/test-e2e-interop/index.ts, src/test-e2e-interop/test.ts
There is a lot of output and it's better to get it as neater files in artifacts than a long and messy stdout.
=> fix(interop): don't log everything by default

src/module/generate-rollup-configuration/index.ts
This commit fixes transpiling other vis libraries in standalone mode.
Here is an example for the vis-network package and targets, which doesn't support ES6 classes. This is also true for other Babel transformations.
**Before:**
```js
...
class SimpleDataPipe {
_source;
_transformers;
_target;
...
```
**After:**
```js
...
var SimpleDataPipe = /*#__PURE__*/function () {
...
```
=> fix(generate-rolup-configuration): add cjs and mjs extensions for plugin-babel

src/generate-examples-index/index.ts
The `globby` package can only handle POSIX style paths, which means that it breaks on Windows when using `path.join()` instead of `path.posix.join()`.
=> fix(generate-examples-index) <1> Globby can only handle POSIX paths
